[build]
  command = "jekyll build && cp _redirects _site/"
  publish = "_site"
  # this enables lunr.js search index generation
  environment = { JEKYLL_ENV = "production" }

# Deploy Preview context: All Deploy Previews
# will inherit these settings.
[context.deploy-preview]
  command = "jekyll build --trace -D --future && cp _redirects _site/"
